plugins {
    id "com.android.application"
}

android {
    namespace "com.suitflow.app"
    compileSdk 35

    defaultConfig {
        applicationId "com.suitflow.app"
        minSdk 24
        targetSdk 35
        versionCode 4
        versionName "1.3.0"
    }

    buildTypes {
        release {
            minifyEnabled true
            shrinkResources true
            proguardFiles getDefaultProguardFile("proguard-android-optimize.txt"), "proguard-rules.pro"
        }
    }
}
